## WEB SCRAPING THE SUN HEADLINES ABOUT MEGHAN MARKLE AND KATE MIDDLETON.

In [1]:
from bs4 import BeautifulSoup
import requests

import pandas as pd
import numpy as np
import re

## MEGHAN MARKLE

In [2]:
meg_sun = pd.DataFrame(columns=['news_source','date','headline', 'url'])

### WEB SCRAPING

In [3]:
site = 'https://www.thesun.co.uk/?s=Meghan+Markle'
result = requests.get(site)
soup = BeautifulSoup(result.text, 'html.parser')

In [4]:
soup.find('div', class_='search-date').text

'23rd June 2021'

In [5]:
publication_dates = [x.text for x in soup.findAll('div', class_='search-date')]

In [6]:
soup.find('p', class_='teaser__subdeck').text

"\n\t\t\tHarry & Meghan 'didn't check with the Queen about legal battle OR trademark'\t\t"

In [8]:
headlines = [x.text for x in soup.findAll('p', class_='teaser__subdeck')]

In [9]:
soup.find('a', class_='text-anchor-wrap').get('href')

'https://www.thesun.co.uk/news/15372923/prince-harry-meghan-markle-queen-trademark/'

In [11]:
article_urls = [x.get('href') for x in soup.findAll('a', class_='text-anchor-wrap')]

In [12]:
soup.find('a', class_='pagination-next').get('href')

'https://www.thesun.co.uk/page/2/?s=Meghan+Markle'

In [13]:
def scrap_article_urls(url):
    
    result = requests.get(url)
    soup = BeautifulSoup(result.text, 'html.parser')
    
    publication_dates = [x.text for x in soup.findAll('div', class_='search-date')]
    headlines = [x.text for x in soup.findAll('p', class_='teaser__subdeck')]
    article_urls = [x.get('href') for x in soup.findAll('a', class_='text-anchor-wrap')]
    
    df = pd.DataFrame(article_urls, columns=['url'])
    df['headline'] = headlines
    df['date'] = publication_dates
    
    try:
        next_url = soup.find('a', class_='pagination-next').get('href')       
        has_next = True
    except:
        has_next = False
        next_url = ''
        
    
    return df, has_next, next_url

In [ ]:
next_url = 'https://www.thesun.co.uk/?s=Meghan+Markle'
has_next = True 


while has_next == True: 
    df, has_next, next_url = scrap_article_urls(next_url)
    meg_sun = meg_sun.append(df)

### CLEANING

In [23]:
meg_sun.reset_index(inplace=True,drop= True)

In [24]:
meg_sun

,news_source,date,headline,url
0,NaN,23rd June 2021,\n\t\t\tPrince William's anger at Meghan Markl...,https://www.thesun.co.uk/fabulous/15267088/roy...
1,NaN,23rd June 2021,\n\t\t\tPrince Harry to 'offer olive branch' &...,https://www.thesun.co.uk/fabulous/15290169/meg...
2,NaN,23rd June 2021,\n\t\t\tHarry & Meghan 'didn't check with the ...,https://www.thesun.co.uk/news/15372923/prince-...
3,NaN,23rd June 2021,"\n\t\t\tWill 'went ballistic when he found ""Do...",https://www.thesun.co.uk/news/15367490/prince-...
4,NaN,23rd June 2021,\n\t\t\tThis Morning's royal expert horrified ...,https://www.thesun.co.uk/tv/15367149/this-morn...
...,...,...,...,...
8941,NaN,20th May 2018,\n\t\t\tMeghan's family celebrate Royal Weddin...,https://www.thesun.co.uk/news/6333254/meghan-m...
8942,NaN,20th May 2018,\n\t\t\tShowbiz pals party at Royal Wedding ba...,https://www.thesun.co.uk/tvandshowbiz/6332414/...
8943,NaN,20th May 2018,\n\t\t\tHuge throng of Royal Wedding fans was ...,https://www.thesun.co.uk/news/6333245/royal-we...
8944,NaN,20th May 2018,\n\t\t\tHarry marries Meg at Windsor â€” and the...,https://www.thesun.co.uk/news/6333100/prince-h...
8945,NaN,20th May 2018,\n\t\t\tHarry and Meghan's wedding tweeted abo...,https://www.thesun.co.uk/news/6333088/harry-an...

In [25]:
meg_sun['news_source'] = 'TheSun'

In [28]:
meg_sun['headline'] = meg_sun['headline'].str[4:]

In [39]:
meg_sun['headline'] = meg_sun['headline'].str[:-2]

In [40]:
meg_sun

,news_source,date,headline,url
0,TheSun,23rd June 2021,Prince William's anger at Meghan Markle 'Dossi...,https://www.thesun.co.uk/fabulous/15267088/roy...
1,TheSun,23rd June 2021,Prince Harry to 'offer olive branch' & bring A...,https://www.thesun.co.uk/fabulous/15290169/meg...
2,TheSun,23rd June 2021,Harry & Meghan 'didn't check with the Queen ab...,https://www.thesun.co.uk/news/15372923/prince-...
3,TheSun,23rd June 2021,"Will 'went ballistic when he found ""Dossier of...",https://www.thesun.co.uk/news/15367490/prince-...
4,TheSun,23rd June 2021,This Morning's royal expert horrified by DEATH...,https://www.thesun.co.uk/tv/15367149/this-morn...
...,...,...,...,...
8941,TheSun,20th May 2018,Meghan's family celebrate Royal Wedding in BUR...,https://www.thesun.co.uk/news/6333254/meghan-m...
8942,TheSun,20th May 2018,Showbiz pals party at Royal Wedding bash - but...,https://www.thesun.co.uk/tvandshowbiz/6332414/...
8943,TheSun,20th May 2018,Huge throng of Royal Wedding fans was so big i...,https://www.thesun.co.uk/news/6333245/royal-we...
8944,TheSun,20th May 2018,Harry marries Meg at Windsor â€” and there's so ...,https://www.thesun.co.uk/news/6333100/prince-h...
8945,TheSun,20th May 2018,Harry and Meghan's wedding tweeted about 3.4MI...,https://www.thesun.co.uk/news/6333088/harry-an...

In [42]:
meg_sun.to_csv('meg_thesun.csv')

In [64]:
meg_thesun = pd.read_csv('meg_thesun.csv', index_col=0)

In [65]:
meg_thesun

,news_source,date,headline,url
0,TheSun,23rd June 2021,Prince William's anger at Meghan Markle 'Dossi...,https://www.thesun.co.uk/fabulous/15267088/roy...
1,TheSun,23rd June 2021,Prince Harry to 'offer olive branch' & bring A...,https://www.thesun.co.uk/fabulous/15290169/meg...
2,TheSun,23rd June 2021,Harry & Meghan 'didn't check with the Queen ab...,https://www.thesun.co.uk/news/15372923/prince-...
3,TheSun,23rd June 2021,"Will 'went ballistic when he found ""Dossier of...",https://www.thesun.co.uk/news/15367490/prince-...
4,TheSun,23rd June 2021,This Morning's royal expert horrified by DEATH...,https://www.thesun.co.uk/tv/15367149/this-morn...
...,...,...,...,...
8941,TheSun,20th May 2018,Meghan's family celebrate Royal Wedding in BUR...,https://www.thesun.co.uk/news/6333254/meghan-m...
8942,TheSun,20th May 2018,Showbiz pals party at Royal Wedding bash - but...,https://www.thesun.co.uk/tvandshowbiz/6332414/...
8943,TheSun,20th May 2018,Huge throng of Royal Wedding fans was so big i...,https://www.thesun.co.uk/news/6333245/royal-we...
8944,TheSun,20th May 2018,Harry marries Meg at Windsor â€” and there's so ...,https://www.thesun.co.uk/news/6333100/prince-h...
8945,TheSun,20th May 2018,Harry and Meghan's wedding tweeted about 3.4MI...,https://www.thesun.co.uk/news/6333088/harry-an...

#### REMOVING ARTICLES NOT ABOUT MEGHAN

In [67]:
meg_thesun = meg_thesun[meg_thesun['headline'].str.contains('Meghan')]

In [68]:
meg_thesun.reset_index(inplace=True,drop= True)

#### DROPPING DUPLICATE HEADLINES

In [69]:
meg_thesun[meg_thesun.duplicated(['headline'], keep = False)]

,news_source,date,headline,url
1101,TheSun,12th June 2020,Who is Meghan Markleâ€™s best friend Jessica Mul...,https://www.thesun.co.uk/tvandshowbiz/11851650...
1403,TheSun,21st January 2020,"Royal News: Meghan Markle, Prince Harry, the Q...",https://www.thesun.co.uk/fabulous/10783166/roy...
1429,TheSun,18th January 2020,"Royal News: Meghan Markle, Prince Harry, the Q...",https://www.thesun.co.uk/fabulous/10765744/meg...
1547,TheSun,10th January 2020,Who is Meghan Markleâ€™s best friend Jessica Mul...,https://www.thesun.co.uk/fabulous/5450951/jess...
1616,TheSun,17th November 2017,"Kate & Wills include pics of Harry, Meghan & A...",https://www.thesun.co.uk/uncategorized/4939291...
1617,TheSun,31st December 2019,"Kate & Wills include pics of Harry, Meghan & A...",https://www.thesun.co.uk/fabulous/10647180/kat...
1629,TheSun,15th November 2017,Meghan & Harry wish their fans a â€˜very Merry C...,https://www.thesun.co.uk/video/uncategorized/p...
1630,TheSun,25th December 2019,Meghan & Harry wish their fans a â€˜very Merry C...,https://www.thesun.co.uk/fabulous/10618660/meg...
2558,TheSun,12th April 2019,Meghan is keeping up with Kim Kardashian as sh...,https://www.thesun.co.uk/fabulous/8841645/megh...
2746,TheSun,25th February 2019,Meghan is keeping up with Kim Kardashian as sh...,https://www.thesun.co.uk/fabulous/8501525/megh...

In [70]:
meg_thesun.drop_duplicates(subset = 'headline', inplace = True)

<ipython-input-70-fa7a186f9fb6>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meg_thesun.drop_duplicates(subset = 'headline', inplace = True)

In [73]:
meg_thesun.reset_index(inplace=True,drop= True)

In [74]:
meg_thesun

,news_source,date,headline,url
0,TheSun,23rd June 2021,Prince William's anger at Meghan Markle 'Dossi...,https://www.thesun.co.uk/fabulous/15267088/roy...
1,TheSun,23rd June 2021,Harry & Meghan 'didn't check with the Queen ab...,https://www.thesun.co.uk/news/15372923/prince-...
2,TheSun,23rd June 2021,This Morning's royal expert horrified by DEATH...,https://www.thesun.co.uk/tv/15367149/this-morn...
3,TheSun,23rd June 2021,Meghan Markle wrote book about her freckles wh...,https://www.thesun.co.uk/fabulous/15366622/meg...
4,TheSun,22nd June 2021,"Queen, 95, has â€˜spring in her stepâ€™ despite Ha...",https://www.thesun.co.uk/news/15361106/queen-s...
...,...,...,...,...
4092,TheSun,20th May 2018,Meghan Markle's Suits co-stars reveal pics fro...,https://www.thesun.co.uk/tvandshowbiz/6333417/...
4093,TheSun,20th May 2018,Meghan dazzles in Stella McCartney dress & Dia...,https://www.thesun.co.uk/fabulous/6330751/megh...
4094,TheSun,20th May 2018,Moment Meghan Markle spots her old teacher in ...,https://www.thesun.co.uk/news/6332952/meghan-m...
4095,TheSun,20th May 2018,Meghan's family celebrate Royal Wedding in BUR...,https://www.thesun.co.uk/news/6333254/meghan-m...
4096,TheSun,20th May 2018,Harry and Meghan's wedding tweeted about 3.4MI...,https://www.thesun.co.uk/news/6333088/harry-an...

#### CLEANING DATE COLUMN

In [89]:
meg_thesun['date'] = meg_thesun['date'].str[-4:]

<ipython-input-89-36414e6d857c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meg_thesun['date'] = meg_thesun['date'].str[-4:]

In [90]:
meg_thesun

,news_source,date,headline,url
0,TheSun,2021,Prince William's anger at Meghan Markle 'Dossi...,https://www.thesun.co.uk/fabulous/15267088/roy...
1,TheSun,2021,Harry & Meghan 'didn't check with the Queen ab...,https://www.thesun.co.uk/news/15372923/prince-...
2,TheSun,2021,This Morning's royal expert horrified by DEATH...,https://www.thesun.co.uk/tv/15367149/this-morn...
3,TheSun,2021,Meghan Markle wrote book about her freckles wh...,https://www.thesun.co.uk/fabulous/15366622/meg...
4,TheSun,2021,"Queen, 95, has â€˜spring in her stepâ€™ despite Ha...",https://www.thesun.co.uk/news/15361106/queen-s...
...,...,...,...,...
4092,TheSun,2018,Meghan Markle's Suits co-stars reveal pics fro...,https://www.thesun.co.uk/tvandshowbiz/6333417/...
4093,TheSun,2018,Meghan dazzles in Stella McCartney dress & Dia...,https://www.thesun.co.uk/fabulous/6330751/megh...
4094,TheSun,2018,Moment Meghan Markle spots her old teacher in ...,https://www.thesun.co.uk/news/6332952/meghan-m...
4095,TheSun,2018,Meghan's family celebrate Royal Wedding in BUR...,https://www.thesun.co.uk/news/6333254/meghan-m...
4096,TheSun,2018,Harry and Meghan's wedding tweeted about 3.4MI...,https://www.thesun.co.uk/news/6333088/harry-an...

### SAVING TO CSV

In [92]:
meg_thesun.to_csv('meg_thesun2.csv')

## KATE MIDDLETON

### WEBSCRAPING

In [44]:
kate_thesun = pd.DataFrame(columns=['news_source','date','headline', 'url'])

In [45]:
next_url = 'https://www.thesun.co.uk/?s=Kate+Middleton'
has_next = True 


while has_next == True: 
    df, has_next, next_url = scrap_article_urls(next_url)
    kate_thesun = kate_thesun.append(df)

In [46]:
kate_thesun.reset_index(inplace=True,drop= True)

In [47]:
kate_thesun

,news_source,date,headline,url
0,NaN,23rd June 2021,\n\t\t\tMeghan Markle & Prince Harry movie dub...,https://www.thesun.co.uk/fabulous/15375274/meg...
1,NaN,23rd June 2021,\n\t\t\tQueen's Kate & Willsâ€™ photo pride of p...,https://www.thesun.co.uk/fabulous/15374336/que...
2,NaN,23rd June 2021,\n\t\t\tMeghan infuriated Will & Kate with her...,https://www.thesun.co.uk/news/15374107/meghan-...
3,NaN,23rd June 2021,\n\t\t\tHarry 'furious' after being 'shunted a...,https://www.thesun.co.uk/news/15373075/harry-f...
4,NaN,23rd June 2021,"\n\t\t\tWill 'went ballistic when he found ""Do...",https://www.thesun.co.uk/news/15367490/prince-...
...,...,...,...,...
5188,NaN,7th January 2015,\n\t\t\tGales of 100mph to batter Britain as j...,https://www.thesun.co.uk/archives/news/6512/10...
5189,NaN,31st October 2015,\n\t\t\tVine: Iâ€™m not trying to be funny\t\t,https://www.thesun.co.uk/archives/news/111603/...
5190,NaN,13th January 2016,\n\t\t\tFormer X-Factor judge Louis Walsh to m...,https://www.thesun.co.uk/archives/tv-old/11109...
5191,NaN,20th April 2011,\n\t\t\tOur Arthur's Top 50 royal pictures\t\t,https://www.thesun.co.uk/news/500021/our-arthu...
5192,NaN,4th January 2015,\n\t\t\tWATCH all the goals and major incident...,https://www.thesun.co.uk/archives/news/4294/ca...

### CLEANING

In [48]:
kate_thesun['news_source'] = 'TheSun'

In [49]:
kate_thesun

,news_source,date,headline,url
0,TheSun,23rd June 2021,\n\t\t\tMeghan Markle & Prince Harry movie dub...,https://www.thesun.co.uk/fabulous/15375274/meg...
1,TheSun,23rd June 2021,\n\t\t\tQueen's Kate & Willsâ€™ photo pride of p...,https://www.thesun.co.uk/fabulous/15374336/que...
2,TheSun,23rd June 2021,\n\t\t\tMeghan infuriated Will & Kate with her...,https://www.thesun.co.uk/news/15374107/meghan-...
3,TheSun,23rd June 2021,\n\t\t\tHarry 'furious' after being 'shunted a...,https://www.thesun.co.uk/news/15373075/harry-f...
4,TheSun,23rd June 2021,"\n\t\t\tWill 'went ballistic when he found ""Do...",https://www.thesun.co.uk/news/15367490/prince-...
...,...,...,...,...
5188,TheSun,7th January 2015,\n\t\t\tGales of 100mph to batter Britain as j...,https://www.thesun.co.uk/archives/news/6512/10...
5189,TheSun,31st October 2015,\n\t\t\tVine: Iâ€™m not trying to be funny\t\t,https://www.thesun.co.uk/archives/news/111603/...
5190,TheSun,13th January 2016,\n\t\t\tFormer X-Factor judge Louis Walsh to m...,https://www.thesun.co.uk/archives/tv-old/11109...
5191,TheSun,20th April 2011,\n\t\t\tOur Arthur's Top 50 royal pictures\t\t,https://www.thesun.co.uk/news/500021/our-arthu...
5192,TheSun,4th January 2015,\n\t\t\tWATCH all the goals and major incident...,https://www.thesun.co.uk/archives/news/4294/ca...

In [59]:
kate_thesun['headline'] = kate_thesun['headline'].str[4:-2]

In [60]:
kate_thesun

,news_source,date,headline,url
0,TheSun,23rd June 2021,Meghan Markle & Prince Harry movie dubbed a â€˜j...,https://www.thesun.co.uk/fabulous/15375274/meg...
1,TheSun,23rd June 2021,Queen's Kate & Willsâ€™ photo pride of place whi...,https://www.thesun.co.uk/fabulous/15374336/que...
2,TheSun,23rd June 2021,Meghan infuriated Will & Kate with her demands...,https://www.thesun.co.uk/news/15374107/meghan-...
3,TheSun,23rd June 2021,Harry 'furious' after being 'shunted aside' wi...,https://www.thesun.co.uk/news/15373075/harry-f...
4,TheSun,23rd June 2021,"Will 'went ballistic when he found ""Dossier of...",https://www.thesun.co.uk/news/15367490/prince-...
...,...,...,...,...
5188,TheSun,7th January 2015,Gales of 100mph to batter Britain as jet strea...,https://www.thesun.co.uk/archives/news/6512/10...
5189,TheSun,31st October 2015,Vine: Iâ€™m not trying to be funny,https://www.thesun.co.uk/archives/news/111603/...
5190,TheSun,13th January 2016,Former X-Factor judge Louis Walsh to make TV c...,https://www.thesun.co.uk/archives/tv-old/11109...
5191,TheSun,20th April 2011,Our Arthur's Top 50 royal pictures,https://www.thesun.co.uk/news/500021/our-arthu...
5192,TheSun,4th January 2015,WATCH all the goals and major incidents from t...,https://www.thesun.co.uk/archives/news/4294/ca...

In [61]:
kate_thesun.to_csv('kate_thesun.csv')

In [75]:
kate_thesun = pd.read_csv('kate_thesun.csv', index_col=0)

In [76]:
kate_thesun

,news_source,date,headline,url
0,TheSun,23rd June 2021,Meghan Markle & Prince Harry movie dubbed a â€˜j...,https://www.thesun.co.uk/fabulous/15375274/meg...
1,TheSun,23rd June 2021,Queen's Kate & Willsâ€™ photo pride of place whi...,https://www.thesun.co.uk/fabulous/15374336/que...
2,TheSun,23rd June 2021,Meghan infuriated Will & Kate with her demands...,https://www.thesun.co.uk/news/15374107/meghan-...
3,TheSun,23rd June 2021,Harry 'furious' after being 'shunted aside' wi...,https://www.thesun.co.uk/news/15373075/harry-f...
4,TheSun,23rd June 2021,"Will 'went ballistic when he found ""Dossier of...",https://www.thesun.co.uk/news/15367490/prince-...
...,...,...,...,...
5188,TheSun,7th January 2015,Gales of 100mph to batter Britain as jet strea...,https://www.thesun.co.uk/archives/news/6512/10...
5189,TheSun,31st October 2015,Vine: Iâ€™m not trying to be funny,https://www.thesun.co.uk/archives/news/111603/...
5190,TheSun,13th January 2016,Former X-Factor judge Louis Walsh to make TV c...,https://www.thesun.co.uk/archives/tv-old/11109...
5191,TheSun,20th April 2011,Our Arthur's Top 50 royal pictures,https://www.thesun.co.uk/news/500021/our-arthu...
5192,TheSun,4th January 2015,WATCH all the goals and major incidents from t...,https://www.thesun.co.uk/archives/news/4294/ca...

#### REMOVING ARTICLES NOT ABOUT KATE

In [78]:
kate_thesun = kate_thesun[kate_thesun['headline'].str.contains('Kate')]

In [80]:
kate_thesun.reset_index(inplace=True,drop= True)

#### DROPPING DUPLICATE HEADLINES

In [81]:
kate_thesun[kate_thesun.duplicated(['headline'], keep = False)]

,news_source,date,headline,url
590,TheSun,21st January 2020,"Royal News: Meghan Markle, Prince Harry, the Q...",https://www.thesun.co.uk/fabulous/10783166/roy...
593,TheSun,18th January 2020,"Royal News: Meghan Markle, Prince Harry, the Q...",https://www.thesun.co.uk/fabulous/10765744/meg...
627,TheSun,17th November 2017,"Kate & Wills include pics of Harry, Meghan & A...",https://www.thesun.co.uk/uncategorized/4939291...
628,TheSun,31st December 2019,"Kate & Wills include pics of Harry, Meghan & A...",https://www.thesun.co.uk/fabulous/10647180/kat...
673,TheSun,3rd December 2019,"Royal news: The Queen, Kate Middleton, Prince ...",https://www.thesun.co.uk/fabulous/10470271/roy...
679,TheSun,30th November 2019,"Royal news: The Queen, Kate Middleton, Prince ...",https://www.thesun.co.uk/fabulous/10451944/roy...
907,TheSun,23rd May 2019,Why does Kate wear so many plasters? Duchess s...,https://www.thesun.co.uk/fabulous/9135479/kate...
1211,TheSun,9th November 2018,Why does Kate wear so many plasters? Duchess s...,https://www.thesun.co.uk/fabulous/7705195/kate...

In [82]:
kate_thesun.drop_duplicates(subset = 'headline', inplace = True)

<ipython-input-82-79d8b39fe33a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kate_thesun.drop_duplicates(subset = 'headline', inplace = True)

In [84]:
kate_thesun.reset_index(inplace=True,drop= True)

In [85]:
kate_thesun

,news_source,date,headline,url
0,TheSun,23rd June 2021,Queen's Kate & Willsâ€™ photo pride of place whi...,https://www.thesun.co.uk/fabulous/15374336/que...
1,TheSun,23rd June 2021,Meghan infuriated Will & Kate with her demands...,https://www.thesun.co.uk/news/15374107/meghan-...
2,TheSun,23rd June 2021,Kate 'helping Prince William and Harry put on ...,https://www.thesun.co.uk/news/15366513/kate-he...
3,TheSun,22nd June 2021,Kate shares honey made by her own bees with ki...,https://www.thesun.co.uk/news/15358079/kate-mi...
4,TheSun,22nd June 2021,Wills & Kate 'did not meet Harry after funeral...,https://www.thesun.co.uk/news/15352118/william...
...,...,...,...,...
1629,TheSun,10th June 2016,Kate Middleton dazzles in a cobalt gown at a b...,https://www.thesun.co.uk/news/1259940/kate-mid...
1630,TheSun,31st May 2016,Male stripper performs in front of pupils as y...,https://www.thesun.co.uk/news/1218955/male-str...
1631,TheSun,25th May 2016,Kate Middleton recycles outfit for annual Buck...,https://www.thesun.co.uk/tvandshowbiz/1202793/...
1632,TheSun,17th May 2016,Spot the difference: Royal princess seen walki...,https://www.thesun.co.uk/news/1198123/spot-the...
1633,TheSun,14th April 2016,The Indian seamstress earning Â£75 a month who ...,https://www.thesun.co.uk/news/1197218/the-indi...

#### CLEANING DATE COLUMN

In [87]:
kate_thesun['date'] = kate_thesun['date'].str[-4:]

<ipython-input-87-92e9599b9b0a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kate_thesun['date'] = kate_thesun['date'].str[-4:]

In [91]:
kate_thesun

,news_source,date,headline,url
0,TheSun,2021,Queen's Kate & Willsâ€™ photo pride of place whi...,https://www.thesun.co.uk/fabulous/15374336/que...
1,TheSun,2021,Meghan infuriated Will & Kate with her demands...,https://www.thesun.co.uk/news/15374107/meghan-...
2,TheSun,2021,Kate 'helping Prince William and Harry put on ...,https://www.thesun.co.uk/news/15366513/kate-he...
3,TheSun,2021,Kate shares honey made by her own bees with ki...,https://www.thesun.co.uk/news/15358079/kate-mi...
4,TheSun,2021,Wills & Kate 'did not meet Harry after funeral...,https://www.thesun.co.uk/news/15352118/william...
...,...,...,...,...
1629,TheSun,2016,Kate Middleton dazzles in a cobalt gown at a b...,https://www.thesun.co.uk/news/1259940/kate-mid...
1630,TheSun,2016,Male stripper performs in front of pupils as y...,https://www.thesun.co.uk/news/1218955/male-str...
1631,TheSun,2016,Kate Middleton recycles outfit for annual Buck...,https://www.thesun.co.uk/tvandshowbiz/1202793/...
1632,TheSun,2016,Spot the difference: Royal princess seen walki...,https://www.thesun.co.uk/news/1198123/spot-the...
1633,TheSun,2016,The Indian seamstress earning Â£75 a month who ...,https://www.thesun.co.uk/news/1197218/the-indi...

### SAVING TO CSV

In [93]:
kate_thesun.to_csv('kate_thesun2.csv')